### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by jaredbidlow** [blastdan/Wox.Plugin.Choco#1]
I get this error message every time i try to run this plugin in Wox

> The closed type Wox.Plugin.Choco.ChocoReference.V2FeedPackage does not have a corresponding ProjectSourceUrl settable property.

**Comment by blastdan** [comment]
I've been meaning for a while to get in and update this. I have noticed the plugin. It functioning in the way I wanted it to for some time. I'll see if I can get into this week and make a fix. 

Thanks for sending me the issue.

**Comment by blastdan** [comment]
Hey Jared
Looks like chocolatey updated the API over time.

I have updated this issue and added the new version to the wox plugin directory. Please install the update and try again.

Thanks!
