### ISSUE TITLE
Choco plugin hangs forever

### ISSUE THREAD

**Issue by MatanRubin** [blastdan/Wox.Plugin.Choco#2]
Installed the plugin, trying to type "choco atom" and the plugin hangs forever.
Anything I can do to debug the issue?

**Comment by blastdan** [comment]
Most likely the service endpoint needs to be updated. Whenever the service definition changes I need to updated it or the thing crashes. Probably a better solution, but that's what it is for now.

**Comment by blastdan** [comment]
Updated the plugin today. Seems to be working a bit better, not perfect but working.
