### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by MiChAeLoKGB** [blastdan/Wox.Plugin.Choco#3]
Every time I try to run the plugin I get this error:

`The closed type Wox.Plugin.Choco.ChocoReference.V2FeedPackage does not have a corresponding IsApproved settable property.`

**Comment by blastdan** [comment]
It hasn't been working for a while. I forgot my login information to the wox plugin store to remove the plugin and the site doesn't have a password reset option. 

Chocolatey has upgraded to v3 of the api as well so the upgrade isn't as easy as I thought it would be.

I also haven't used wox in years so I have very little incentive to try and fix it.

**Comment by MiChAeLoKGB** [comment]
Well, that quite sad, but I do get it tho... I hope you or somebody fixes this plugin, because it was really nice to be able to see plugins that mached te string as you typed...


May I ask, what have you replaced Vox with, if anything?

**Comment by blastdan** [comment]
I actually just updated it to see how the new Odata Client was working. Everything should be working now as well as it was before. Still really slow as I have to index the images...

I didn't replace wox with anything. I never found that the project was stable enough for the program to become required in my workflow.
