### ISSUE TITLE
does not work anymore

### ISSUE THREAD

**Issue by noneym** [blastdan/Wox.Plugin.Choco#4]
does not work anymore. probably because of api. 
https://chocolatey.org/api/v2/
if you want i can create unofficial api

**Comment by blastdan** [comment]
I think i have it fixed. The odata service seemed to not be running on TLS, so I have added that line of code in. Seems like it's updated.

**Comment by blastdan** [comment]
@noneym Can you confirm that the updated plug-in is now working?
